/*
 * board_types.h
 *
 *  Created on: Mar 22, 2023
 *      Author: abolinaga
 */

#ifndef SENOSR_TYPES_H_
#define SENOSR_TYPES_H_

#include "sensors_types.h"
#include "protocol_types.h"
#include "time_sync_types.h"

#include "pl_types.h"
#include "pl_time.h"
#include "pl_event.h"
#include "pl_queue.h"

#define SYSTEM_MODEL	"energy"

/* Event (error or alerts) codes of the system */
#define CODE_NO_ERROR_CODE_SPECIFIED			1
#define CODE_INVALID_EVENT_TYPE					2
#define CODE_INVALID_SENSOR_SERVICE				3
#define CODE_WATCHDOG_RESET						4
#define CODE_TO_MANY_READ_EVENT_TIMEOUT			5
#define CODE_ADE9000_RECONFIG					7
#define CODE_ADE9000_REGISTER_READ_ERROR		7
#define CODE_ADE9000_REGISTER_WRITE_ERROR		8
#define CODE_ADE9000_BURST_READ_ERROR			9
#define CODE_ADE9000_WAVEFORM_DATA_LOST			10
#define CODE_ADE9000_REGISTERS_DATA_LOST		11
#define CODE_TIME_NOT_SYNCRHONIZED				12
#define CODE_FW_DETECTED						13
#define CODE_NO_FW_DETECTED						14
#define CODE_FLASH_ERASE_FAILED					15
#define CODE_FLASH_WRITING_FAILED				16
#define CODE_FLASH_AREA_EXCEEDED				17
#define CODE_ERROR_SENDING_DISCOVERY			18
#define CODE_ERROR_SENDING_STATUS				19
#define CODE_ERROR_INVALID_CMD					20
#define CODE_ERROR_RESET_NOT_ACCEPTED			21
#define CODE_ERROR_START_NOT_ACCEPTED			22
#define CODE_ERROR_STOP_NOT_ACCEPTED			23
#define CODE_ERROR_UPDATE_INCORRECT_STATE		24
#define CODE_ERROR_RECONFIGURED					25
#define CODE_ERROR_GETTING_CMD					26
#define CODE_ADE9000_INVALID_FUND_FREQ			27
#define CODE_ADE9000_REGISTER_NOT_WRITTEN		28
#define CODE_ADE9000_INVALID_HW_CONFIG			29
#define CODE_ADE9000_INVALID_TC_VALUES			30
#define CODE_ADE9000_IRQ_NOT_WORKING			31
#define CODE_UNKNOWN_PROTOCOL					32
#define CODE_UNKNOWN_FORMAT						33
#define CODE_UDP_NOT_SEND						34
#define CODE_UDP_SENDING_ERROR					35
#define CODE_FW_UPDATE_DISCONNECTION			36
#define CODE_FW_UPDATE_AREA_NOT_EMPTY			37
#define CODE_FW_UPDATE_ERASED					38
#define CODE_FW_UPDATE_INCOPATIBLE_MAGIC_NUM	39
#define CODE_FW_UPDATE_INCOPATIBLE_HEADER		40
#define CODE_FW_UPDATE_IMAGE_SIZE_NOK			41
#define CODE_FW_UPDATE_INCOPATIBLE_BOOT			42
#define CODE_TCP_NOT_SEND						43
#define CODE_TCP_SENDING_ERROR					44
#define CODE_FAST_VARS_QUEUE_FULL				45
#define CODE_SLOW_VARS_QUEUE_FULL				46
#define CODE_QUEUE_DATA_NOT_OBTAINED			47
#define CODE_FAST_VARS_COULD_NOT_START			48
#define CODE_SLOW_VARS_COULD_NOT_START			49
#define CODE_NOT_CONNTECTED_WITH_TCP_SERVER		50
#define CODE_NOT_RECONNTECTED_WITH_TCP_SERVER	51
#define CODE_MQTT_RX_BUFF_FULL					52
#define CODE_SERVICE_ALREADY_RUNNING			53
#define CODE_SERVICE_ALREADY_STOPPED			54
#define CODE_POWERUP_RESET						55
#define CODE_SECURITY_RESET						56
#define CODE_SW_RESET							57
#define CODE_JTAG_HW_RESET						58
#define CODE_JTAG_SW_RESET						59
#define CODE_TEMP_SENSE_RESET					60
#define CODE_TIME_SYNCRHONIZED					61
#define CODE_INCORRECT_MANU_DATA				62
#define CODE_INCORRECT_MANU_ID					63
#define CODE_INCORRECT_MANU_MAC					64
#define CODE_INCORRECT_MANU_MODEL				65
#define CODE_MANU_MODEL_EMPTY					66
#define CODE_MANU_BOARD_EMPTY					67
#define CODE_MANU_SERIAL_EMPTY					68
#define CODE_MANU_MANUFACTURER_EMPTY			69
#define CODE_MANU_VERSION_EMPTY					70
#define CODE_UNKNOWN_COMM_FORMAT				71
#define CODE_UNKNOWN_COMM_PROTOCOL				72
#define CODE_TRYING_TO_READ_WITH_NO_PROT		73
#define CODE_TIME_SYNC_PROCESS_ERROR			74
#define CODE_FLASH_ERASE_TIMEOUT_ERROR			75
#define CODE_STATE_CHNAGE_DATA_RX_TIMEOUT		76
#define CODE_ALERT_JSON_OBTAINING_ERROR			77
#define CODE_TS_JSON_OBTAINING_ERROR			78
#define CODE_INFO_JSON_OBTAINING_ERROR			79
#define CODE_SENSOR_STATUS_JSON_ERROR			80
#define CODE_UNKNOWN_SENSOR_STATUS				81
#define CODE_SERVICE_STATUS_JSON_ERROR			82
#define CODE_UNKNOWN_SERVICE_STATUS				83
#define CODE_UNKNOWN_REG_TYPE					84
#define CODE_INCORRECT_FUND_FREQ_ERROR			85
#define CODE_INCORRECT_TC_ERROR					86
#define CODE_UNKNOWN_SYNC_TYPE					87
#define CODE_INVALID_VARS_CONFIG				88
#define CODE_UNKNOWN_FW_SLOT					89
#define CODE_NO_SERVICE_VARS_CONFIG				90
#define CODE_NO_SERVICE_TX_CONFIG				91
#define CODE_INCORRECT_REG_NOT_FOUND			92
#define CODE_REGISTERS_NOT_READ					93
#define CODE_INCORRECT_IP_CONFIGURED			94
#define CODE_FWU_DONE_FAIL						95
#define CODE_FWU_STARTED_FAIL					96
#define CODE_HARDFAULT_GENERIC_RESET			97
#define CODE_HARDFAULT_NMI_RESET				98
#define CODE_HARDFAULT_MEM_MAN_RESET			99
#define CODE_HARDFAULT_BUS_RESET				100
#define CODE_HARDFAULT_USAGE_RESET				101
#define CODE_HARDFAULT_SVC_RESET				102
#define CODE_HARDFAULT_DEBUGMON_RESET			103
#define CODE_HARDFAULT_PENDSV_RESET				104
#define CODE_HARDFAULT_SYSTICK_RESET			105
#define CODE_HARDFAULT_INTHAND_RESET			106
#define CODE_HARDFAULT_STACKOF_RESET			107
#define CODE_HARDFAULT_MALLOC_RESET				108
#define CODE_HARDFAULT_ASSERT_RESET				109
#define CODE_HARDFAULT_THREAD_CREATE_RESET		110
#define CODE_HARDFAULT_THREAD_INIT_RESET		111
#define CODE_HARDFAULT_THREAD_NOT_INIT_RESET	112
#define CODE_HARDFAULT_WDOG_INIT_RESET			113
#define CODE_HARDFAULT_WDOG_NOT_INIT_RESET		114
#define CODE_HARDFAULT_MANU_NOT_INIT_RESET		115
#define CODE_HARDFAULT_DEBUG_NOT_INIT_RESET		116
#define CODE_HARDFAULT_SWITCH_CASE_RESET		117
#define CODE_HARDFAULT_QUEUE_CREATE_RESET		118
#define CODE_HARDFAULT_EVENT_CREATE_RESET		119
#define CODE_HARDFAULT_UNKNOWN_EVENT_RESET		120
#define CODE_HARDFAULT_LAZY_STACKING_RESET		121
#define CODE_HARDFAULT_HEAP_PUSH_RESET			122
#define CODE_HARDFAULT_HEAP_UNSTACK_RESET		123
#define CODE_HARDFAULT_DATA_ACCESS_RESET		124
#define CODE_HARDFAULT_INST_ACCESS_RESET		125
#define CODE_HARDFAULT_BUS_LAZY_STACK_RESET		126
#define CODE_HARDFAULT_BUS_HEAP_STACK_RESET		127
#define CODE_HARDFAULT_BUS_HEAP_UNSTACK_RESET	128
#define CODE_HARDFAULT_IMP_DATA_BUS_RESET		129
#define CODE_HARDFAULT_PRE_DATA_BUS_RESET		130
#define CODE_HARDFAULT_INST_BUS_RESET			131
#define CODE_HARDFAULT_DIVIDED_ZERO_RESET		132
#define CODE_HARDFAULT_UNALIGNED_RESET			133
#define CODE_HARDFAULT_NO_COPROC_RESET			134
#define CODE_HARDFAULT_INVALID_PC_RESET			135
#define CODE_HARDFAULT_INVALID_STATE_RESET		136
#define CODE_HARDFAULT_UNDEF_INST_RESET			137
#define CODE_REGISTERS_READ_LONG_TIME			138
#define CODE_REGISTERS_HIGH_READ_TIME			139
#define CODE_REGISTERS_RAW_HIGH_READ_TIME		140
#define CODE_ERROR_INVALID_CONFIG_PAYLOD		141
#define CODE_ERROR_INVALID_START_PAYLOD			142
#define CODE_ERROR_INVALID_SYNC_PAYLOD			143
#define CODE_ERROR_INVALID_MANU_PAYLOD			144

#ifdef DEBUG_ALERTS
#define CODE_DEBUG_ALERT						1000
#endif

/* system general states */
typedef enum system_states
{
	SYSTEM_INIT_STATE = 0,
	SYSTEM_MANUFACTURING_STATE,
	SYSTEM_WAIT_ETH_LINK_STATE,
	SYSTEM_WAIT_SERVER_STATE,
	SYSTEM_NORMAL_STATE,
	SYSTEM_ERROR_STATE,
	SYSTEM_FW_UPDATE_STATE,
	SYSTEM_STATE_MAXVALUE
}system_states_t;

typedef enum event_type
{
	EVENT_TYPE_INFO = 0,
	EVENT_TYPE_WARNING,
	EVENT_TYPE_ERROR,
	EVENT_TYPE_NONE
}event_type_t;

typedef struct event_info
{
	event_type_t  event_type;
	sensors_t	  sensor;
	services_t	  service;
	error_code_t* error_code;
}event_info_t;

typedef struct fw_update_handling_conf_t
{
	uint32_t 		nvm_primary_index;
    uint32_t 		nvm_secondary_index;
	event_info_t* 	fwu_handling_events_array;
}fw_update_handling_conf_t;

#define MAX_ERROR_CODES 		10

#endif /* SYSTEM_TYPES */
