/*
 * system_init.h
 *
 *  Created on: Mar 22, 2023
 *      Author: abolinaga
 */

#ifndef SYSTEM_INIT_H_
#define SYSTEM_INIT_H_

#include "system_types.h"



typedef enum system_handler_events
{
	SH_EVENTS_WDOG_RESET = 0,
	SH_EVENTS_POWERUP_RESET,
	SH_EVENTS_SECURITY_RESET,
	SH_EVENTS_SOFTWARE_RESET,
	SH_EVENTS_JTAG_HW_RESET,
	SH_EVENTS_JTAG_SW_RESET,
	SH_EVENTS_TEMPSENSE_RESET,
	SH_EVENTS_FW_UPDATE_DISCONNECTION,
	SH_EVENTS_FW_UPDATE_AREA_ERASED,
	SH_EVENTS_UNKNOWN_FAST_COMM_FORMAT,
	SH_EVENTS_UNKNOWN_SLOW_COMM_FORMAT,
	SH_EVENTS_UNKNOWN_FAST_COMM_PROTOCOL,
	SH_EVENTS_UNKNOWN_SLOW_COMM_PROTOCOL,
	SH_EVENTS_TIME_SYNC_PROCESS_ERROR,
	SH_EVENTS_FLASH_AREA_DELETE_ERROR,
	SH_ADE9000_REGISTER_NOT_FOUND,
	SH_GENERIC_HF_ERROR_RESET,
	SH_NMI_HF_ERROR_RESET,
	SH_MEM_MAN_HF_ERROR_RESET,
	SH_BUS_HF_ERROR_RESET,
	SH_USAGE_HF_ERROR_RESET,
	SH_SVC_HF_ERROR_RESET,
	SH_DEBUGMON_HF_ERROR_RESET,
	SH_PENDSV_HF_ERROR_RESET,
	SH_SYSTICK_HF_ERROR_RESET,
	SH_INTHAND_HF_ERROR_RESET,
	SH_STACKOF_HF_ERROR_RESET,
	SH_MALLOC_HF_ERROR_RESET,
	SH_ASSERT_HF_ERROR_RESET,
	SH_THREAD_CREATE_HF_ERROR_RESET,
	SH_THREAD_INIT_HF_ERROR_RESET,
	SH_THREAD_NOT_INIT_HF_ERROR_RESET,
	SH_WDOF_INIT_HF_ERROR_RESET,
	SH_WDOG_NOT_INIT_HF_ERROR_RESET,
	SH_MANU_NOT_INIT_HF_ERROR_RESET,
	SH_DEBUG_SHELL_NOT_INIT_HF_ERROR_RESET,
	SH_SWITCH_CASE_HF_ERROR_RESET,
	SH_QUEUE_CREATE_HF_ERROR_RESET,
	SH_EVENT_CREATE_HF_ERROR_RESET,
	SH_UNKNOWN_EVENT_HF_ERROR_RESET,
	SH_LAZY_STACKING_MPU_HF_ERROR_RESET,
	SH_HEAP_PUSH_HF_ERROR_RESET,
	SH_HEAP_UNSTACK_HF_ERROR_RESET,
	SH_DATA_ACCSESS_HF_ERROR_RESET,
	SH_INST_ACCSESS_HF_ERROR_RESET,
	SH_LAZY_STACKING_BUS_HF_ERROR_RESET,
	SH_BUS_HEAP_STACK_HF_ERROR_RESET,
	SH_BUS_HEAP_UNSTACK_HF_ERROR_RESET,
	SH_IMP_DATA_BUS_HF_ERROR_RESET,
	SH_PRE_DATA_BUS_HF_ERROR_RESET,
	SH_INST_BUS_HF_ERROR_RESET,
	SH_DIVIDED_ZERO_HF_ERROR_RESET,
	SH_UNALIGNED_ACCESS_HF_ERROR_RESET,
	SH_NO_COPROC_HF_ERROR_RESET,
	SH_INVALID_PC_HF_ERROR_RESET,
	SH_INVALID_STATE_HF_ERROR_RESET,
	SH_UNDEF_INST_HF_ERROR_RESET,
	SH_ADE9000_REGISTER_HIGH_READ_TIME,
	SH_ADE9000_REGISTERS_AND_RAW_HIGH_READ_TIME,
	SH_EVENTS_MAXVALUE
}system_handler_events_t;

void system_handler(void *arg);

uint32_t system_get_tc_primary_config(void);

uint32_t system_get_tc_secondary_config(void);

energy_fundamental_freq_t system_get_fund_freq_config(void);

bool system_get_high_pass_filter_config(void);

energy_hw_config_t system_get_hw_config(void);

sync_type_t system_sync_get_sync_type(void);

absl_time_t system_sync_get_sync_period(void);

bool system_get_current_a_invert(void);

bool system_get_current_b_invert(void);

bool system_get_current_c_invert(void);

void system_get_adc_redirect(uint32_t* _adc_redirect);

float system_get_slow_vars_period(void);

#endif /* SYSTEM_INIT_H_ */
